AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - db/migrate/*
Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  # Enabled: false
  # Change the default 80 chars limit value
  Max: 140
    # If you want the rule only apply to a specific folder/file
  # Include:
  # - 'app/**/*'
  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - test/**/**

Metrics/MethodLength:
  Max: 25
  Exclude:
    - test/**/**
    - spec/**/**
    - db/migrate/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always
  Exclude:
    - test/**/**
    - spec/**/**
    - db/migrate/*
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - test/**/**
    - spec/**/**
    - db/migrate/*
    - db/schema.rb