development:
  adapter: redis
  url: <%= ENV['REDIS_HOST'] %>
  channel_prefix: drunk_quiz_production

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_HOST'] %>
  channel_prefix: drunk_quiz_production
