default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # https://guides.rubyonrails.org/configuring.html#database-pooling
  host: <%= ENV['DATABASE_HOST'] %> # localhost DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase" https://guides.rubyonrails.org/configuring.html#configuring-a-database
  port: 5432 # The TCP port the server listens on. Defaults to 5432.

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME']}_test" %>

production:
  <<: *default
