name: Deploy to Heroku
on:
  push:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "drunk-quiz" #Must be unique in Heroku
          heroku_email: "e_den9611@live.com"
          branch: "main"
          healthcheck: https://drunk-quiz.herokuapp.com
          delay: 5